name: Build, Test, and Release

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Clean build directory
      run: |
        rm -rf build
        mkdir build

    - name: Configure with CMake
      run: |
        cmake -B build -S .

    - name: Build project
      run: |
        cmake --build build

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure

  release:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Clean build directory
      run: |
        rm -rf build
        mkdir build

    - name: Configure with CMake
      run: |
        cmake -B build -S .

    - name: Build and package
      run: |
        cmake -B build -S.
        cmake --build build --config Release
        cpack -B build -G DEB
    
    - name: Upload release artifact
      uses: actions/upload-release-asset@v1.0.2
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: package/helloworld-*.deb
        asset_name: helloworld.deb
        content_type: application/x-debian-package
